Add live-kit-improved overlayfs-testing files. Thanks goes to johndah4x0r for code.

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -25,6 +25,19 @@ get_exclude()
     done
 }
 
+get_lowerdirs()
+{
+	local BUND_DIRS BUND_EXT BUND
+	BUND_DIRS="$1"
+	BUND_EXT="$2"
+	MNT_OPT=""
+
+	MNT_OPT="$(find "$BUND_DIRS" -depth -type d | sed '$ d' | grep ".$BUND_EXT" | \
+	while read BUND; do echo -n "${BUND}:"; done)"
+	MNT_OPT="${MNT_OPT%?}"
+	echo "$MNT_OPT"
+}
+
 # NOTE: DO NOT TOUCH THE ESCAPE CHARACTERS!
 BLUE="[1;34m"
 YELLOW="[1;33m"
@@ -37,28 +50,28 @@ NC="[0m"
 # debug related
 debug_start()
 {
-   if grep -q 'debug' /proc/cmdline; then
-      DEBUG_IS_ENABLED=1
-   else
-      DEBUG_IS_ENABLED=
-   fi
+    if grep -q 'debug' /proc/cmdline; then
+        DEBUG_IS_ENABLED=1
+    else
+        DEBUG_IS_ENABLED=
+    fi
 }
 
 dbg_shell_start()
 {
-   if grep -q 'dbg_shell' /proc/cmdline; then
-       DBG_SHELL=1
-   else
-       DBG_SHELL=
-   fi
+    if grep -q 'dbg_shell' /proc/cmdline; then
+        DBG_SHELL=1
+    else
+        DBG_SHELL=
+    fi
 }
 
 debug_log()
 {
-   if [ "$DEBUG_IS_ENABLED" ]; then
-      echo "[${GREEN}"' debug '"${NC}]: $@" >&2
-      log "debug_log: $*"
-   fi
+    if [ "$DEBUG_IS_ENABLED" ]; then
+        echo "[${GREEN}"' debug '"${NC}]: $@" >&2
+        log "debug_log: $*"
+    fi
 }
 
 # echo related functions
@@ -154,9 +167,9 @@ fatal()
 #
 allow_only_root()
 {
-   if [ "0$UID" -ne 0 ]; then
-       echo_err "Only root can run $(basename $0)"; exit 1
-   fi
+    if [ "0$UID" -ne 0 ]; then
+        echo_err "Only root can run $(basename $0)"; exit 1
+    fi
 }
 
 # Make bundle
@@ -231,22 +244,22 @@ init_proc_sysfs()
 # modprobe all modules found in initial ramdisk
 modprobe_everything()
 {
-   debug_log "modprobe_everything" "$*"
+    debug_log "modprobe_everything" "$*"
 
-   echo_livekit_msg "Probing for hardware..." >&2
+    echo_livekit_msg "Probing for hardware..." >&2
 
-   find /lib/modules/ | fgrep '.ko' | xargs -n 1 modprobe 2>/dev/null
-   refresh_devs
+    find /lib/modules/ | fgrep '.ko' | xargs -n 1 modprobe 2>/dev/null
+    refresh_devs
 }
 
 
 refresh_devs()
 {
-   debug_log "refresh_devs" "$*"
-   if [ -r /proc/sys/kernel/hotplug ]; then
-      echo /sbin/mdev > /proc/sys/kernel/hotplug
-   fi
-   mdev -s
+    debug_log "refresh_devs" "$*"
+    if [ -r /proc/sys/kernel/hotplug ]; then
+        echo /sbin/mdev > /proc/sys/kernel/hotplug
+    fi
+    mdev -s
 }
 
 # make sure some devices are there
@@ -266,104 +279,34 @@ init_devs()
 #
 init_zram()
 {
-   debug_log "init_zram" "$*"
-   echo_livekit_msg "Setting up ZRAM as swap if available..."
-   if [ -r /sys/block/zram0/disksize ]; then
+    debug_log "init_zram" "$*"
+    echo_livekit_msg "Setting up ZRAM as swap if available..."
+    if [ -r /sys/block/zram0/disksize ]; then
       echo 536870912 > /sys/block/zram0/disksize # 512MB
-      mkswap /dev/zram0 >/dev/null
-      swapon /dev/zram0 -p 32767
-      echo 100 > /proc/sys/vm/swappiness
-   fi
-}
-
-# load the AUFS kernel module if needed
-#
-init_aufs()
-{
-    debug_log "init_aufs" "$*"
-
-    # Prepare for error messages
-    echo >>/var/log/livekit-log
-
-    modprobe aufs 2>/var/log/livekit-log
-    AUFS_ENABLED=1
-
-    # If aufs module failed to load, switch to overlayfs
-    if [ $? -ne 0 ]; then
-		OVERLAY_ENABLED=1
-		unset AUFS_ENABLED
-        #fatal "Failed to load AUFS module!"
+        mkswap /dev/zram0 >/dev/null
+        swapon /dev/zram0 -p 32767
+        echo 100 > /proc/sys/vm/swappiness
     fi
-
-    # finally, refresh all devices
-    refresh_devs
 }
 
-# load the OVERLAY kernel module if needed
+# Load OverlayFS kernel module
 #
-init_overlay()
+modprobe_overlay()
 {
-    debug_log "init_overlay" "$*"
-    # TODO maybe check here if aufs support is working at all
-    # and produce useful error message if user has no aufs
-    
+    debug_log "modprobe_overlay" "$*"
+
     # Prepare for error messages
-    echo >>/var/log/livekit-log
-    
+    echo >>/var/log/livkekit-log
+
     modprobe overlay 2>/var/log/livekit-log
-   
-    # If aufs module failed to load, panic immidiately
+
+    # If overlay module failed to load, panic immidiately
     if [ $? -ne 0 ]; then
-        fatal "Failed to load OVERLAYFS module!"
+        fatal "Failed to load OverlayFS module!"
     fi
 
     # finally, refresh all devices
     refresh_devs
-    OVERLAY_ENABLED=1
-}
-
-# Setup empty union for aufs
-# $1 = changes directory (ramfs or persistent changes)
-# $2 = union directory where to mount the union
-#
-init_union_aufs()
-{
-   debug_log "init_union" "$*"
-
-   echo_livekit_msg "Initialising AUFS union..."
-   mkdir -p "$1"
-   mkdir -p "$2"
-
-   # Prepare for error messages
-   echo >>/var/log/livekit-log
-
-   mount -t aufs -o xino="/.xino",trunc_xino,br="$1" aufs "$2" >>/var/log/livekit-log 2>&1
-   # If failed to init union, panic
-   if [ $? -ne 0 ]; then
-       fatal "Failed to initialise AUFS union!"
-   fi
-}
-
-# Setup empty union for aufs
-# $1 = changes directory (ramfs or persistent changes)
-# $2 = union directory where to mount the union
-#
-init_union_overlayfs()
-{
-   debug_log "init_union_overlayfs" "$*"
-
-   echo_livekit_msg "Initialising OVERLAYFS union..."
-   mkdir -p "$1"
-   mkdir -p "$2"
-
-   # Prepare for error messages
-   echo >>/var/log/livekit-log
-
-   #mount -t aufs -o xino="/.xino",trunc_xino,br="$1" aufs "$2" >>/var/log/livekit-log 2>&1
-   # If failed to init union, panic
-   #if [ $? -ne 0 ]; then
-   #    fatal "Failed to initialise AUFS union!"
-   #fi
 }
 
 # Return device mounted for given directory
@@ -630,7 +573,6 @@ persistent_changes()
 
     # If persistent changes are not requested, end here
     if grep -vq 'perch' /proc/cmdline; then
-        NOCHANGE="yes"
         return
     fi
 
@@ -746,96 +688,54 @@ sortmod()
 
 # Mount squashfs filesystem bundles
 # and add them to union
+# NEW: Prepare Overlay file system
 # $1 = directory where to search for bundles
 # $2 = directory where to mount bundles
-mount_append_bundles()
+# $3 = directory where the changes is
+# $4 = directory where union is supposed to be
+#
+prepare_overlay()
 {
-    debug_log "mount_append_bundles" "$*"
+    debug_log "prepare_overlay" "$*"
 
-    local BUN
+    local BUN ALL_BUNDS LOWERDIR UPPERDIR WORKDIR
 
-    echo_livekit >&2
-    echo "Appending bundles for union setup..." >&2
-
+    echo_livekit_msg "Preparing OverlayFS union..." >&2
+    echo >>/var/log/livekit-log
     # Just tell me why! Why be compact?!?
     ( ls -1 "$1" | sort -n ; cd "$1" ; find modules/ 2>/dev/null | \
     sortmod | filter_load) | grep '[.]'$BEXT'$' |\
     filter_noload | \
     while read BUNDLE; do
-        echo_livekit_msg "Appending: $BUNDLE" >&2
-
         BUN="$(basename "$BUNDLE")"
+        echo_livekit_msg "Mounting $BUN to /memory/bundles..." >&2
         mkdir -p "$2/$BUN"
 
         # It now depends on your kernel!
         mount -o loop -t squashfs "$1/$BUNDLE" "$2/$BUN"
     done
-}
 
-# Add modules to aufs union
-# $1 = mounted bundle folder
-# $2 = directory where union is mounted
-add_to_aufs_union_bundles()
-{
-	debug_log "add_to_aufs_union_bundles" "$*"
-	local BUN
-	mount -o remount,add:1:"$1" aufs "$2"
-}
+    ALL_BUNDS="$(get_lowerdirs "$2" "$BEXT")"
+    LOWERDIR="/memory/lowerdir"
+    UPPERDIR="$3"
+    WORKDIR="${UPPERDIR}/.workdir"
 
-# Mount squashfs filesystem bundles
-# and add them to union
-# $1 = directory where to search for bundles
-# $2 = directory where to mount bundles
-# $3 = directory where union is mounted
-#
-union_append_bundles()
-{
-    debug_log "union_append_bundles" "$*"
+    # Make the workdir (cuz it's non-existant, yet...)
+    mkdir "$WORKDIR" >/dev/null 2>&1
 
-    local BUN
+    # I think this is a work-around
+    # Separating 2 commands to avoid overflow (aka avoid triggering "Argument list to long" error)
+    mkdir "$LOWERDIR" >/dev/null 2>&1
+    mount -t overlay -o lowerdir="$ALL_BUNDS" overlay "$LOWERDIR" >>/var/log/livekit-log 2>&1 && \
+    mount -t overlay -o lowerdir="$LOWERDIR",upperdir="$UPPERDIR",workdir="$WORKDIR" \
+    overlay "$4" >>/var/log/livekit-log 2>&1
 
-    echo_livekit >&2
-    echo "Appending bundles to union..." >&2
-
-    # Just tell me why! Why be compact?!?
-    ( ls -1 "$1" | sort -n ; cd "$1" ; find modules/ 2>/dev/null | \
-    sortmod | filter_load) | grep '[.]'$BEXT'$' |\
-    filter_noload | \
-    while read BUNDLE; do
-        echo_livekit_msg "Appending: $BUNDLE" >&2
-
-        BUN="$(basename "$BUNDLE")"
-        mkdir -p "$2/$BUN"
-
-        # It now depends on your kernel!
-        mount -o loop -t squashfs "$1/$BUNDLE" "$2/$BUN"
-        mount -o remount,add:1:"$2/$BUN" aufs "$3"
-    done
-}
-
-# Mount squashfs filesystem bundles
-# and add them to union
-# $1 = directory where to search for bundles
-# $2 = directory where to mount bundles
-# $3 = directory where module path is
-#
-mount_append_bundles_modpath()
-{
-   debug_log "mount_append_bundles_modpath" "$*"
-
-   local BUN MOD
-   echo_livekit >&2
-   MOD="$3"
-   echo "Adding modpath ${MOD}/ bundles for union setup.."
-   ( ls -1 "$1" | sort -n ; cd "$1" ; find "${MOD}"/ 2>/dev/null | \
-   sortmod | filter_load) | grep '[.]'$BEXT'$' |\
-   filter_noload | \
-   while read BUNDLE; do
-      echo_livekit_msg "Appending: $BUNDLE" >&2
-      BUN="$(basename "$BUNDLE")"
-      mkdir -p "$2/$BUN"
-      mount -o loop -t squashfs "$1/$BUNDLE" "$2/$BUN"
-   done
+    # Check if we got any errors...
+    if [ $? -ne 0 ]; then
+    	fatal "Failed to prepare OverlayFS union!"
+    else
+    	echo_livekit_msg "And we have lift-off!" >&2
+    fi
 }
 
 # Create empty fstab properly
@@ -847,28 +747,13 @@ fstab_create()
 
     local FSTAB
     FSTAB="$1/etc/fstab"
+    echo overlay / overlay defaults 0 0 > $FSTAB
     echo proc /proc proc defaults 0 0 >> $FSTAB
     echo sysfs /sys sysfs defaults 0 0 >> $FSTAB
     echo devpts /dev/pts devpts gid=5,mode=620 0 0 >> $FSTAB
     echo tmpfs /dev/shm tmpfs defaults 0 0 >> $FSTAB
 }
 
-fstab_create_aufs()
-{
-	debug_log "fstab_create_aufs" "$*"
-	local FSTAB
-	FSTAB="$1/etc/fstab"
-	echo aufs / aufs defaults 0 0 > $FSTAB
-}
-
-
-fstab_create_overlay()
-{
-	debug_log "fstab_create_overlay" "$*"
-	local FSTAB
-	FSTAB="$1/etc/fstab"
-	echo overlay / overlay defaults 0 0 > $FSTAB
-}
 
 # Change root and execute init
 # $1 = where to change root
@@ -885,32 +770,25 @@ change_root()
     # make sure important device files and directories are in union
     mkdir -p boot dev proc sys tmp mnt run
     chmod 1777 tmp
-    if [ ! -e $UNION/dev/console ]; then mknod dev/console c 5 1; fi
-    if [ ! -e $UNION/dev/tty ]; then mknod dev/tty c 5 0; fi
-    if [ ! -e $UNION/dev/tty0 ]; then mknod dev/tty0 c 4 0; fi
-    if [ ! -e $UNION/dev/tty1 ]; then mknod dev/tty1 c 4 1; fi
-    if [ ! -e $UNION/dev/null ]; then mknod dev/null c 1 3; fi
-    if [ ! -e $UNION/sbin/fsck.aufs ]; then ln -s /bin/true sbin/fsck.aufs; fi
+    if [ ! -e dev/console ]; then mknod dev/console c 5 1; fi
+    if [ ! -e dev/tty ]; then mknod dev/tty c 5 0; fi
+    if [ ! -e dev/tty0 ]; then mknod dev/tty0 c 4 0; fi
+    if [ ! -e dev/tty1 ]; then mknod dev/tty1 c 4 1; fi
+    if [ ! -e dev/null ]; then mknod dev/null c 1 3; fi
 
     # find chroot and init
-    if [ -x $UNION/bin/chroot -o -L $UNION/bin/chroot ]; then  CHROOT=bin/chroot; fi
-    if [ -x $UNION/sbin/chroot -o -L $UNION/sbin/chroot ]; then  CHROOT=sbin/chroot; fi
-    if [ -x $UNION/usr/bin/chroot -o -L $UNION/usr/bin/chroot ]; then  CHROOT=usr/bin/chroot; fi
-    if [ -x $UNION/usr/sbin/chroot -o -L $UNION/usr/sbin/chroot ]; then CHROOT=usr/sbin/chroot; fi
+    if [ -x bin/chroot -o -L bin/chroot ]; then  CHROOT=bin/chroot; fi
+    if [ -x sbin/chroot -o -L sbin/chroot ]; then  CHROOT=sbin/chroot; fi
+    if [ -x usr/bin/chroot -o -L usr/bin/chroot ]; then  CHROOT=usr/bin/chroot; fi
+    if [ -x usr/sbin/chroot -o -L usr/sbin/chroot ]; then CHROOT=usr/sbin/chroot; fi
     if [ "$CHROOT" = "" ]; then fatal "chroot: Executable not found!"; fi
 
-    if [ -x $UNION/bin/init -o -L $UNION/bin/init ]; then INIT=bin/init; fi
-    if [ -x $UNION/sbin/init -o -L $UNION/sbin/init  ]; then INIT=sbin/init; fi
+    if [ -x bin/init -o -L bin/init ]; then INIT=bin/init; fi
+    if [ -x sbin/init -o -L sbin/init  ]; then INIT=sbin/init; fi
     if [ "$INIT" = "" ]; then fatal "init: Executable not found!"; fi
 
     mkdir -p mnt/live
-    if [ "$AUFS_ENABLED" ]; then
-		mount -n -o remount,ro aufs .
-	fi
-	if [ "$OVERLAY_ENABLED" ]; then
-		mount -n -o remount,ro overlay .
-	fi
-	
+    mount -n -o remount,ro overlay .
     pivot_root . mnt/live
     exec $CHROOT . $INIT < dev/console > dev/console 2>&1
 }
